"""initial schema

Revision ID: 276e1ad62555
Revises: 
Create Date: 2026-07-15 15:14:37.836392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '276e1ad62555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facebook_page_id', sa.String(length=100), nullable=True),
    sa.Column('facebook_app_access_token', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_shops_owner_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_slug'), 'shops', ['slug'], unique=True)
    op.create_table('customers',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('facebook_user_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'phone', name='uq_customers_shop_phone')
    )
    op.create_table('ingredients',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'piece', 'box', name='ingredient_unit'), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('last_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingredients_shop', 'ingredients', ['shop_id'], unique=False)
    op.create_table('menu_categories',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_shop_id'), 'menu_categories', ['shop_id'], unique=False)
    op.create_table('users',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'cashier', name='user_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'email', name='uq_users_shop_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_shop_id'), 'audit_logs', ['shop_id'], unique=False)
    op.create_table('ingredient_logs',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_logs_ingredient_id'), 'ingredient_logs', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_ingredient_logs_shop_id'), 'ingredient_logs', ['shop_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_items_shop', 'menu_items', ['shop_id'], unique=False)
    op.create_table('orders',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'preparing', 'ready', 'completed', 'cancelled', name='order_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'stripe', name='payment_method'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', name='payment_status'), nullable=False),
    sa.Column('delivery_type', sa.Enum('pickup', 'delivery', name='delivery_type'), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('estimated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.Enum('web_form', 'facebook_messenger', 'direct_admin', name='order_source'), nullable=False),
    sa.Column('messenger_user_id', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_shop_created', 'orders', ['shop_id', 'created_at'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['shop_id', 'status'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_table('transactions',
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('order', 'refund', 'expense', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_shop_date', 'transactions', ['shop_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_shop_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_shop_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_menu_items_shop', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_ingredient_logs_shop_id'), table_name='ingredient_logs')
    op.drop_index(op.f('ix_ingredient_logs_ingredient_id'), table_name='ingredient_logs')
    op.drop_table('ingredient_logs')
    op.drop_index(op.f('ix_audit_logs_shop_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_menu_categories_shop_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index('idx_ingredients_shop', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('customers')
    op.drop_index(op.f('ix_shops_slug'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
