"""order item unit cost

Revision ID: 75119d6879fd
Revises: 276e1ad62555
Create Date: 2026-07-15 15:50:26.603712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75119d6879fd'
down_revision: Union[str, Sequence[str], None] = '276e1ad62555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_foreign_key('fk_shops_owner_id', 'shops', 'users', ['owner_id'], ['id'], use_alter=True)
    # Backfill existing rows from the current menu cost (best effort; new rows snapshot at creation)
    op.execute(
        "UPDATE order_items oi SET unit_cost = mi.cost "
        "FROM menu_items mi WHERE oi.menu_item_id = mi.id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shops_owner_id', 'shops', type_='foreignkey')
    op.drop_column('order_items', 'unit_cost')
    # ### end Alembic commands ###
