"""paynow and postal code

Revision ID: 7bcea14ef7e2
Revises: e3c7db31d776
Create Date: 2026-07-16 21:22:51.132531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcea14ef7e2'
down_revision: Union[str, Sequence[str], None] = 'e3c7db31d776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('postal_code', sa.String(length=12), nullable=True))
    # Autogenerate can't detect enum value additions (allowed in a transaction on PG >= 12)
    op.execute("ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'paynow'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'postal_code')
    # ### end Alembic commands ###
